### ISSUE TITLE
Alorese Pandai geminate n

### ISSUE THREAD

**Issue by OwenAmarasi** [Anaphory/lexirumah-data#124]
Alorese Pandai geminate nː is rendered as _m_ in the orthography column rather than _nn_

**Comment by Anaphory** [comment]
That's because of this typo:
https://github.com/lessersunda/lexirumah-data/blob/659620ab0c7d0009ca4346598795b5b75b5f1c1a/cldf/p/alor1247-pandai#L8

That orthography profile generally maps geminates to single letters, not double letters, though: So should it be `nn` or just `n`? If nn is correct, should the other cases also be `rr`, `kk`, etc.?

**Comment by OwenAmarasi** [comment]
It should just be single <n>, I think. (unlike what I said in the earlier
post)

So just that typo needs to be fixed.

All the best,
Owen

**Comment by Anaphory** [comment]
Good, will do!
