### ISSUE TITLE
Some initial apostrophes might have gone missing at some point

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexirumah-data#54]
Opening CSV files in *Office is a problem. Some word-initial `'` might have gone missing.

**Comment by OwenAmarasi** [comment]
Yes. Initial glottal stops in all languages which use ' for glottal stop in the orthography and given as. This includes Amarasi (created a separate issue) and many languages of Flores which contrast #V and #ʔV words (e.g. Ende, Lamholot varieteis).

Is there a smart way to isolate all instances of [ʔ] in the form column word initially so that we (I...) can determine which initial glottal stops need to be marked in the orthography and given as column.

Languages which lost stress marking are less of a concern for me.
